import { getSupabaseAdmin } from "@/lib/supabase";
import { get as storageGet, put } from "@/lib/storage";
import { toCsv, num } from "@/lib/csv";
import { createZip } from "@/lib/zip";
import { planAttachments, packageName } from "@/lib/submission-naming";
import { logInfo, logWarn } from "@/lib/logger";

/**
 * Build the package accounts actually receives.
 *
 * The CSV is the spine and the receipts folder sits beside it. The
 * `receipt_file` column holds the exact filename, so a row and its receipt
 * pair by string match with no cross-referencing — that is the whole point of
 * the format, and why filenames are generated by tested pure functions.
 */

const CSV_COLUMNS = [
  { key: "stmt_line", header: "stmt_line" },
  { key: "txn_date", header: "txn_date" },
  { key: "post_date", header: "post_date" },
  { key: "merchant", header: "merchant" },
  { key: "descriptor", header: "descriptor" },
  { key: "amount_inr", header: "amount_inr", value: (r) => num(r.amount_inr) },
  { key: "currency", header: "currency" },
  { key: "amount_orig", header: "amount_orig", value: (r) => num(r.amount_orig) },
  { key: "fx_rate", header: "fx_rate", value: (r) => (r.fx_rate ? num(r.fx_rate, 4) : "") },
  { key: "type", header: "type" },
  { key: "category", header: "category" },
  { key: "receipt_file", header: "receipt_file" },
  { key: "receipt_status", header: "receipt_status" },
  { key: "declared_reason", header: "declared_reason" },
  { key: "tax_id", header: "tax_id" },
  { key: "tax_amount", header: "tax_amount", value: (r) => num(r.tax_amount) },
  { key: "invoice_no", header: "invoice_no" },
  { key: "trip", header: "trip" },
];

// Comfortably inside typical mail gateway limits once base64 encoding adds ~33%.
const MAX_ZIP_BYTES = 20 * 1024 * 1024;

/**
 * Gather every charge in the cycle with its receipt, build CSV + ZIP, store it,
 * and record a draft submission. Sending is a separate, explicit step.
 */
export async function buildSubmission({ userId, cycle, force = false }) {
  const sb = getSupabaseAdmin();

  const verification = await verifyAgainstStatement({ userId, cycle, force });

  const { data: txns } = await sb
    .from("transactions")
    .select("*")
    .eq("user_id", userId)
    .gte("date", cycle.cycle_start)
    .lte("date", cycle.cycle_end)
    .order("date", { ascending: true });

  const transactions = txns || [];
  if (!transactions.length) {
    throw new Error(`No transactions in cycle ${cycle.cycle_start} → ${cycle.cycle_end}`);
  }

  // Where a statement has been reconciled, its line numbers are the ones
  // accounts will be checking against, so they become the CSV's spine.
  const linesByTxn = await statementLinesByTransaction(userId, verification.statementId);

  // Which receipt is attached to which charge.
  const { data: links } = await sb
    .from("receipt_transactions")
    .select("receipt_id, transaction_id")
    .in(
      "transaction_id",
      transactions.map((t) => t.id)
    );

  const receiptIds = [...new Set((links || []).map((l) => l.receipt_id))];
  const { data: receiptRows } = receiptIds.length
    ? await sb.from("receipts").select("*").in("id", receiptIds)
    : { data: [] };

  const receiptsById = new Map((receiptRows || []).map((r) => [r.id, r]));

  // References run in charge order, so R-001 is the earliest. A charge may
  // carry two bills and a bill may cover two charges; both survive here.
  const plan = planAttachments(transactions, links, receiptsById);

  const files = [];
  const rows = [];
  let attached = 0;
  const skipped = [];
  const dropped = new Set();

  for (const file of plan.files) {
    try {
      files.push({ name: `receipts/${file.name}`, data: await receiptBytes(file.receipt) });
      attached += 1;
    } catch (err) {
      // A missing object must not sink the whole package — report it instead.
      skipped.push({ receiptId: file.receiptId, error: err.message });
      dropped.add(file.name);
      await logWarn({
        source: "submission",
        event: "receipt_fetch_failed",
        userId,
        message: `Could not read the file for ${file.receiptId.slice(0, 8)}`,
        details: { error: err.message },
      });
    }
  }

  for (const [i, t] of transactions.entries()) {
    // Only files that actually made it into the zip may be cited, or accounts
    // is sent looking for something that is not there.
    const names = (plan.namesByTxn.get(t.id) || []).filter((n) => !dropped.has(n));

    // Two bills for one charge are both cited, separated so the column still
    // pairs with the folder by plain string matching.
    const filename = names.join("; ");

    // The rest of the row describes the charge, so it takes its detail from
    // the first bill attached to it.
    const receipt = plan.files.find((f) => f.name === names[0])?.receipt || null;

    const stmtLine = linesByTxn.get(t.id) || null;

    rows.push({
      stmt_line: stmtLine?.line_no ?? i + 1,
      txn_date: stmtLine?.txn_date ?? t.date,
      post_date: stmtLine?.post_date ?? t.date,
      merchant: t.merchant,
      descriptor: stmtLine?.descriptor ?? t.merchant,
      amount_inr: t.amount,
      currency:
        stmtLine?.currency ||
        (receipt?.currency && receipt.currency !== "INR" ? receipt.currency : "INR"),
      amount_orig:
        stmtLine?.amount_orig ??
        (receipt?.currency && receipt.currency !== "INR" ? receipt.amount : null),
      fx_rate: receipt?.fx_rate || null,
      type: t.is_refund ? "refund" : "purchase",
      category: t.category,
      receipt_file: filename,
      receipt_status: filename ? "attached" : t.receipt_status || "missing",
      declared_reason: t.declared_reason || "",
      tax_id: receipt?.tax_id || "",
      tax_amount: receipt?.tax_total ?? null,
      invoice_no: receipt?.invoice_no || "",
      trip: "",
    });
  }

  const csv = toCsv(rows, CSV_COLUMNS);
  const csvName = packageName(cycle.card, cycle, "csv").replace("VIP_CorpCard", "reconciliation");
  files.unshift({ name: csvName, data: Buffer.from(csv, "utf8") });

  const zip = createZip(files);
  const zipName = packageName(cycle.card, cycle, "zip");

  if (zip.length > MAX_ZIP_BYTES) {
    await logWarn({
      source: "submission",
      event: "package_large",
      userId,
      message: `Package is ${(zip.length / 1024 / 1024).toFixed(1)} MB — may bounce`,
    });
  }

  const zipPath = `${userId}/submissions/${zipName}`;
  await put(zipPath, zip, { contentType: "application/zip" });

  const total = transactions.filter((t) => !t.is_refund).reduce((s, t) => s + Number(t.amount || 0), 0);
  const chaseable = transactions.filter(
    (t) => !t.is_refund && Number(t.amount) >= (cycle.card?.min_receipt_amount ?? 500)
  );
  // Coverage counts charges that have a bill, not bills: two receipts against
  // one dinner cover one charge, and would otherwise read as two.
  const covered = rows.filter((r) => r.receipt_file).length;
  const coverage = chaseable.length ? Math.round((covered / chaseable.length) * 100) : 100;

  const { data: submission, error } = await sb
    .from("submissions")
    .insert({
      user_id: userId,
      cycle_id: cycle.id,
      zip_path: zipPath,
      csv_path: csvName,
      line_count: transactions.length,
      receipt_count: attached,
      coverage_pct: coverage,
      total_amount: total,
      status: "draft",
      sent_to: cycle.card?.accounts_email || [],
    })
    .select()
    .single();

  if (error) throw new Error(`submission insert failed: ${error.message}`);

  await logInfo({
    source: "submission",
    event: "built",
    userId,
    message: `Package built: ${transactions.length} lines, ${attached} receipts, ${coverage}%`,
    details: { zipName, bytes: zip.length, skipped: skipped.length },
  });

  return {
    submission,
    zip,
    zipName,
    csv,
    stats: {
      lines: transactions.length,
      attached,
      coverage,
      total,
      skipped,
      verified: verification.verified,
      statementNote: verification.note,
    },
  };
}

/**
 * The tie-out gate.
 *
 * The strongest claim this package makes to accounts is that it reconciles to
 * the bank's own statement. So a cycle whose statement does not balance is
 * refused outright — a package that quietly ships a number nobody can explain
 * is worse than no package at all. A cycle with no statement yet is allowed
 * through, but says so, because the alternative is stranding a submission on a
 * bank email that never arrived.
 */
async function verifyAgainstStatement({ userId, cycle, force }) {
  const { data: statement } = await getSupabaseAdmin()
    .from("statements")
    .select("id, issued_on, tie_out_diff, status")
    .eq("user_id", userId)
    .eq("cycle_id", cycle.id)
    .order("issued_on", { ascending: false })
    .limit(1)
    .maybeSingle();

  if (!statement) {
    return {
      verified: false,
      statementId: null,
      note: "No statement has been reconciled for this cycle — figures are the app's own, not the bank's.",
    };
  }

  const diff = Number(statement.tie_out_diff ?? 0);
  const tiesOut = statement.status === "reconciled" && Math.abs(diff) <= 0.5;

  if (!tiesOut && !force) {
    throw new Error(
      statement.status === "reconciled"
        ? `Statement ${statement.issued_on} does not tie out — off by ₹${Math.abs(diff).toFixed(2)}. The cycle is blocked until that is explained.`
        : `Statement ${statement.issued_on} has not been reconciled yet.`
    );
  }

  return {
    verified: tiesOut,
    statementId: statement.id,
    note: tiesOut
      ? `Reconciles to the statement issued ${statement.issued_on}.`
      : `Sent despite a tie-out gap of ₹${Math.abs(diff).toFixed(2)}.`,
  };
}

async function statementLinesByTransaction(userId, statementId) {
  if (!statementId) return new Map();

  const { data } = await getSupabaseAdmin()
    .from("statement_lines")
    .select("line_no, txn_date, post_date, descriptor, currency, amount_orig, transaction_id")
    .eq("statement_id", statementId)
    .not("transaction_id", "is", null);

  return new Map((data || []).map((l) => [l.transaction_id, l]));
}

/**
 * The bytes that go in the package.
 *
 * The cleaned copy when there is one — deskewed, cropped, grey on white, which
 * is what a person filing an expense claim expects to see. The original is
 * still in storage and is what a tax enquiry would be shown; it is simply not
 * what accounts wants to read.
 */
async function receiptBytes(receipt) {
  const scan = receipt?.extracted?.scan;
  if (scan?.path) {
    try {
      return await storageGet(scan.path);
    } catch {
      // Fall through: a package with the photograph beats no package at all.
    }
  }
  return storageGet(receipt.storage_path);
}
